COMPANIES = [
    {"name": "Reliance Industries", "ticker": "RELIANCE", "sector": "Conglomerate"},
    {"name": "Tata Consultancy Services", "ticker": "TCS", "sector": "IT Services"},
    {"name": "Infosys", "ticker": "INFY", "sector": "IT Services"},
    {"name": "HDFC Bank", "ticker": "HDFCBANK", "sector": "Banking"},
    {"name": "ICICI Bank", "ticker": "ICICIBANK", "sector": "Banking"},
    {"name": "State Bank of India", "ticker": "SBIN", "sector": "Banking"},
    {"name": "Larsen & Toubro", "ticker": "LT", "sector": "Engineering & Construction"},
    {"name": "Bharti Airtel", "ticker": "BHARTIARTL", "sector": "Telecom"},
    {"name": "ITC", "ticker": "ITC", "sector": "FMCG"},
    {"name": "Hindustan Unilever", "ticker": "HINDUNILVR", "sector": "FMCG"},
    {"name": "Axis Bank", "ticker": "AXISBANK", "sector": "Banking"},
    {"name": "Kotak Mahindra Bank", "ticker": "KOTAKBANK", "sector": "Banking"},
    {"name": "HCL Technologies", "ticker": "HCLTECH", "sector": "IT Services"},
    {"name": "Wipro", "ticker": "WIPRO", "sector": "IT Services"},
    {"name": "Asian Paints", "ticker": "ASIANPAINT", "sector": "Consumer"},
    {"name": "Maruti Suzuki India", "ticker": "MARUTI", "sector": "Automobiles"},
    {"name": "Sun Pharmaceutical Industries", "ticker": "SUNPHARMA", "sector": "Pharmaceuticals"},
    {"name": "Titan Company", "ticker": "TITAN", "sector": "Consumer"},
    {"name": "Bajaj Finance", "ticker": "BAJFINANCE", "sector": "Financial Services"},
    {"name": "UltraTech Cement", "ticker": "ULTRACEMCO", "sector": "Cement"},
]
